### ISSUE TITLE
Cannot measure distance between two worlds. :/

### ISSUE THREAD

**Issue by MADS0LADEN** [DDevilISL/MineMe#1]
`[20:16:00] [Server thread/WARN]: [MineMe] Task #4576 for MineMe v1.5.5 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between Spawn and Mines
    at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at org.bukkit.Location.distance(Location.java:439) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at me.ddevil.mineme.mines.impl.BasicMine.reset(BasicMine.java:679) ~[?:?]
    at me.ddevil.mineme.mines.impl.BasicHologramMine.reset(BasicHologramMine.java:175) ~[?:?]
    at me.ddevil.mineme.thread.PluginLoader$1.run(PluginLoader.java:264) ~[?:?]
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-e22506f]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by MADS0LADEN** [comment]
> It prints this in the console when i reload the plugin and start or stop the server.

**Comment by MADS0LADEN** [comment]
Wrong button. :/

**Comment by DDevilISL** [comment]
Which version are you using?

**Comment by BrunoSilvaFreire** [comment]
Fixed in 1.6
